services:
  database:
    container_name: postgres-sql-server
    image: postgres:17.5-bullseye
    networks:
      - sysacad-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./volumes/data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-juanku} -d ${DB_NAME:-sysacad} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.tcp.routers.database.rule=HostSNI(`*`)"
    #   - "traefik.tcp.routers.database.entrypoints=postgresql"
    #   - "traefik.tcp.services.database.loadbalancer.server.port=5432"
  
networks:
  sysacad-network:
    # name: sysacad-network
    # driver: bridge
    external: true